language: php

php: [5.3.3, 5.3, 5.4, 5.5]

before_script:
  - composer selfupdate
  - composer install --prefer-source

script:
  - bin/phpspec run
  - php scripts/phpcs --standard=PSR1 --report=summary src/
  - php scripts/phpcs --standard=PSR2 --report=summary src/